name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-vle5-app:${{ github.sha }} .

      - name: Test Docker image
        run: |
          docker run -d --name test-app -p 3000:3000 devops-vle5-app:${{ github.sha }}
          sleep 8
          curl --fail http://localhost:3000
          docker stop test-app
          docker rm test-app
